name: sync_star_repro
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.7

dependencies:
  actors: ^0.11.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
